SISPO-developers/sispo

- sispo/compression/compression.py
- sispo/utils.py
Add read_png_image #56
Refactor file extension check into utils method
> Add utils #56

- sispo/simulation/compositor.py
> Add detection of single or multi frame input #47

- sispo/simulation/starcat.py
> Gab sys ind starcat

- sispo/simulation/compositor.py
- sispo/simulation/render.py
- sispo/simulation/simulation.py
> Replace main w sssbonly

- sispo/simulation/compositor.py
- sispo/simulation/render.py
- sispo/simulation/sc.py
- sispo/simulation/simulation.py
> Gab add instrument class

- sispo/simulation/compositor.py
- sispo/simulation/simulation.py
Fix #86 
Fix #90 , compositor runs in up to 3 threads
> Gab sim compose

- sispo/simulation/compositor.py
- sispo/simulation/render.py
- sispo/simulation/simulation.py
Fix #92 
No safety measures taken though but by the way the software is built there should not be access to the same data from different threads
> Gab move comp2render

- sispo/sim/compositor.py
> Adds infobox scaling and error handling #89

- sispo/sispo.py
> Remove double negatives #79

- sispo/compression/compression.py
> Add multithreaded compression #95

- sispo/sim/compositor.py
Fix definitions of x and y axis
Fix condition for "Infobox is bigger than image"
> Move infobox to lower right corner fix #117

- benchmarks/img_proc.py
> Gab  benchmarks

- sispo/compression/compression.py
Add moving .xyz files
Use compression and decompression
Store compressed files to see data amount
Add jpg detection to cv decorator, only 8bit possible
> Fix priors and jp2000 issue

- sispo/compression/compression.py
- sispo/sispo.py
Remove necessity of calling load_images()
> Make compression single image based

- setup.py
- sispo/__init__.py
Similar interface for adding readme to package
> Use single store version of sispo

- sispo/sim/cb.py
- sispo/sim/sim.py
Kiruna team needs velocity vectors. Extended the position history to include velocity vectors. And also made it possible to extend the output later
> print velocities and add possibility to extend output later

- setup.py
- sispo/plugins/plugins.py
- sispo/sispo.py
Hey, I can attach my codes through this "interface"
> Plugin support

- data/input/oneshot_67p.json
- data/input/oneshot_itokawa.json
- sispo/sim/sim.py
and added one-shot image blender rendering input files for 67p and itokawa
> updated itokawa input file with correct relative pose and light direction

- data/input/definition.json
- sispo/sim/cb.py
- sispo/sim/sc.py
- sispo/sim/sim.py
Fixes astropy unit conversion and orekit incompatibility with versions 10 and higher.
> Fix dependencies

- sispo/plugins/plugins.py
- sispo/sim/opengl/rendergl.py
- sispo/sim/render.py
- sispo/sim/sim.py
Simplify rotations and make one-shot image rendering mode work properly for Cycles rendering as well as OpenGL rendering.
> clean up rotations
